### ISSUE TITLE
Image in README.md file not displaying correctly

### ISSUE THREAD

**Issue by Azeezkadiri** [krshoss/azelf#5]
## Description

The image in the `README.md` file is not displaying correctly.

## Steps to Reproduce

1. Open the `README.md` file in a web browser.
2. Observe that the image is not displayed.
3.  Click on the suposed image, it dislays an error 404 page with the following message ; The 'krshkun/azelf' repository doesn't contain the '.github/assets/azelf.png' path in 'main'. 

## Expected Result

The image should be displayed correctly in the `README.md` file.

## Actual Result

The image is not displayed.

## Additional Context

I am using the following browser and operating system:

- Browser: Chrome
- Operating System: Windows

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/krshkun/azelf/blob/main/CODE_OF_CONDUCT.md)

**Comment by devvsakib** [comment]
there is no image named azelf in the assets folder

**Comment by krshkun** [comment]
Yes, there isn't 👍 Will create one in a day or two ✅

**Comment by krshkun** [comment]
Thank you for opening the issue @Azeezkadiri and thank you for validating @devvsakib

**Comment by Azeezkadiri** [comment]
Thanks

**Comment by Azeezkadiri** [comment]
I’m new to open source and this is my first contribution. I hope to be more
valuable in the future to the community 😁

**Comment by krshkun** [comment]
You will sure be! It's noticing these small things that can improve a project that make you a great OSS contributor!
